/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Presentacion;
import dtos.CitaDTO;
import GestionCitas.FGestionCita;
import GestionCitas.IGestionCita;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
/**
 * JDialog para resignar la cita
 * @author JESUS
 */
public class frmReasignar extends javax.swing.JDialog {
    //Objetos y variables de la clase
    private CitaDTO citaAnterior;
    private CitaDTO citaNueva;
    private boolean confirmacion= false;
    private IGestionCita gestion;
    
    /**
     * Creates new form frmReasignar
     */
    public frmReasignar(java.awt.Frame parent, boolean modal,CitaDTO cita) {
        super(parent, modal);
        initComponents();
        this.citaAnterior=cita;
        this.citaNueva=new CitaDTO();
        gestion= new FGestionCita();
        centrarDialogoEnPantalla(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateTimeR = new com.github.lgooddatepicker.components.DateTimePicker();
        btnVerificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REASIGNAR CITA");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jLabel2.setText("SELECCIONA FECHA Y HORA PARA LA CITA");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnVerificar.setText("Verificar");
        btnVerificar.setBackground(new java.awt.Color(204, 204, 204));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setBackground(new java.awt.Color(204, 204, 204));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(dateTimeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerificar)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTimeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        //Variable para poder confirma la fecha si esta 
        //Dispobible
        confirmacion=false;
        if (dateTimeR.getDateTimePermissive() != null && dateTimeR.getDateTimePermissive().getHour()>0) {
            LocalDateTime fechaNueva = dateTimeR.getDateTimePermissive();
             
            Date fechaHoraAnterior = this.citaAnterior.getFechaHora();
            LocalDateTime fechaAnterior = LocalDateTime.ofInstant(fechaHoraAnterior.toInstant(), ZoneId.systemDefault());
            
            if (fechaNueva.isAfter(fechaAnterior)) {
                try {
                    //Realiza la convercion por zona horaria
                    SimpleDateFormat inputFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
                    inputFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
                    String fechaStr = fechaNueva.format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));
                    Date date = inputFormat.parse(fechaStr);
       
                    citaNueva.setCedulaProfesional(this.citaAnterior.getCedulaProfesional());
                    citaNueva.setFechaHora(date);
                    citaNueva.setEstado(true);

                    // Verificar disponibilidad de la nueva fecha antes de proceder
                    CitaDTO citaExistente = gestion.verificarFecha(citaNueva);
                    if (citaExistente == null) {
                        JOptionPane.showMessageDialog(null, "Esta disponible");
                        confirmacion=true;
                    } else {
                        JOptionPane.showMessageDialog(null, "La fecha y hora seleccionadas ya están ocupadas.");
                    }
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "Error al parsear la fecha: " + e.getMessage());
                }
            }else{
                JOptionPane.showMessageDialog(null, "La fecha o hora seleccionada son de dias anteriores");
            }     
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fecha y hora");
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (confirmacion) {
            CitaDTO actualizada=gestion.reasginarCita(citaAnterior, citaNueva);
            if (actualizada!=null) {
                JOptionPane.showMessageDialog(null, "Se ha reasignado la cita");
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(null, "No ha verificado la fecha");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Metodo para centrar el JDialog
     * @param dialog dialog a centrar
     */
    public void centrarDialogoEnPantalla(JDialog dialog) {
        // Obtiene las dimensiones de la pantalla
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcula la nueva posición del JDialog: centrado horizontal y vertical
        int x = (dimension.width - dialog.getWidth()) / 2;
        int y = (dimension.height - dialog.getHeight()) / 2;

        // Establece la nueva posición del JDialog
        dialog.setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVerificar;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimeR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
