package presentacion;

import dtos.MedicoDTO;
import javax.swing.JOptionPane;

/**
 * Clase que representa el formulario del menú principal de la aplicación.
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    /**
     * Medico que inicio la sesion
     */
    private MedicoDTO medicoActivo;

    /**
     * Constructor de la clase FrmMenuPrincipal.
     * Inicializa los componentes del formulario y asigna el médico activo.
     * @param medico Objeto MedicoDTO que representa al médico que ha iniciado sesión.
     */
    public FrmMenuPrincipal(MedicoDTO medico) {
        initComponents();
        this.medicoActivo = medico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnFacturacion = new javax.swing.JButton();
        AgendarCitaBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFacturacion.setBackground(new java.awt.Color(204, 204, 204));
        btnFacturacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFacturacion.setText("Facturacion");
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 177, 58));

        AgendarCitaBtn.setText("Agendar Cita");
        AgendarCitaBtn.setBackground(new java.awt.Color(204, 204, 204));
        AgendarCitaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgendarCitaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarCitaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AgendarCitaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 177, 58));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 710, 350));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 10, 740, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se ejecuta al hacer clic en el botón "Agendar Cita".
     * Abre el formulario para agendar citas y oculta este formulario del menú principal.
     * @param evt Evento de acción generado al hacer clic en el botón "Agendar Cita".
     */
    private void AgendarCitaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarCitaBtnActionPerformed
        FrmCitas citas = new FrmCitas(this, true, medicoActivo);
        citas.setVisible(true);
    }//GEN-LAST:event_AgendarCitaBtnActionPerformed

    /**
     * Metodo que se ejecuta al hacer clic en el boton "Facturar"
     * Abre el formulario para facturacion
     * @param evt Evento de acción generado al hacer clic en el botón "Facturar".
     */
    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        // TODO add your handling code here:
        if (medicoActivo.getDatosFiscales() == null) {
            JOptionPane.showMessageDialog(this, "Se requieren datos para la emision de factura, favor de capturarlos",
                        "Datos incompletos", JOptionPane.INFORMATION_MESSAGE);
            FrmDatosFiscales regReceptor = new FrmDatosFiscales(null, true, null, medicoActivo);
            regReceptor.setVisible(true);
        } else {
            FrmFacturacion facturacion = new FrmFacturacion(this, true, medicoActivo);
            facturacion.setVisible(true);
        }
    }//GEN-LAST:event_btnFacturacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarCitaBtn;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
